name: agendamobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.9.2
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  http: ^0.13.0
  mask_text_input_formatter: ^2.9.0
  whatsapp_unilink: ^2.1.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/pessoaPadraoWhiteMode.png"

flutter:
  uses-material-design: true

  # tornar .env acessível
  assets:
    - .env
    - images/pessoaPadraoWhiteMode.png
