name: agendamobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.7
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.9.2
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/pessoaPadrao.png"

flutter:
  uses-material-design: true
  assets:
    - images/pessoaPadrao.png
